main.c: fix !DEBUG build failure: errorrate, seed
main.c fails to compile with no-DEBUG build:

main.c:331:9: error: ‘errorrate’ undeclared (first use in this function)
main.c:331:26: error: ‘seed’ undeclared (first use in this function)

References to errorrate and seed need to be #ifdef DEBUG.

Signed-off-by: Kamal Mostafa <kamal@whence.com>